version: '3.4'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - yellow-jersey
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    expose:
      - 8081
    ports:
      - "8081:8081"
    networks:
      - yellow-jersey
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongo:27017/

  mock-strava-api:
    container_name: openapi_mock
    image: muonsoft/openapi-mock
    expose:
      - 8082
    environment:
      OPENAPI_MOCK_SPECIFICATION_URL: '/app/openapi.yml'
      OPENAPI_MOCK_PORT: 8082
    networks:
      - yellow-jersey
    volumes:
      - ./openapi.yml:/app/openapi.yml
    ports:
      - "8082:8082"

volumes:
  mongodb_data_container:

networks:
  yellow-jersey: